# -*- coding: utf-8 -*-
"""QuizAnalisis-SantiagoTuberquia

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dcTXzl8l0DvC8PoWYo4gqbnoi0DpswoO

##Recursivo
"""

def menor_lista(l):
  if len(l) == 1:
      return l[0]
  else:
      m = menor_lista(l[1:])
      return m if m < l[0] else l[0]

l = [4,2,6,1] 
menor_lista(l)

"""##No recursivo"""

lista = [] #O(1)
for i in range(5): #O(1)
    valor=int(input("Ingrese valor:")) #O(1)
    lista.append(valor) #O(1)

menor = lista[0] #O(1)
posicion = 0 #O(1) 
for x in range(len(l)): #O(n)
  if lista[x]<menor: #O(1)
    menor = lista[x] #O(1)
    posicion = x #O(1)
print(menor) #O(n)
print("Su complejidad es O(n)")